version: "3"
services:
  mongodb:
    image: mongo:5.0.26-focal
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - db-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongo --username root --password $${MONGO_INITDB_ROOT_PASSWORD} --eval 'db.stats()'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
