name: Docker Compose CI

on:
  push:
    branches:
      - main # Trigger CI on pushes to the main branch

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Validate Docker Compose files
        run: docker compose config -q
