name: Docker Compose CI

on:
  push:
    branches:
      - main # Trigger CI on pushes to the main branch

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Validate Docker Compose files
        run: docker compose config -q
